name: API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          working-directory: apps/api
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Run tests
        run: uv run pytest
